// <auto-generated />
using System;
using C4.Modules.Graph.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Graph.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GraphDbContext))]
    partial class GraphDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C4.Modules.Graph.Domain.ArchitectureGraph.ArchitectureGraph", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("architecture_graphs", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphEdge.GraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchitectureGraphId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureGraphId");

                    b.ToTable("graph_edges", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphNode.GraphNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchitectureGraphId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureGraphId");

                    b.HasIndex("ExternalResourceId", "ArchitectureGraphId")
                        .IsUnique();

                    b.ToTable("graph_nodes", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphSnapshot.GraphSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchitectureGraphId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureGraphId");

                    b.ToTable("graph_snapshots", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphEdge.GraphEdge", b =>
                {
                    b.HasOne("C4.Modules.Graph.Domain.ArchitectureGraph.ArchitectureGraph", null)
                        .WithMany("Edges")
                        .HasForeignKey("ArchitectureGraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("C4.Modules.Graph.Domain.GraphEdge.EdgeProperties", "Properties", b1 =>
                        {
                            b1.Property<Guid>("GraphEdgeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Direction")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("direction");

                            b1.Property<int>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("port");

                            b1.Property<string>("Protocol")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("protocol");

                            b1.HasKey("GraphEdgeId");

                            b1.ToTable("graph_edges");

                            b1.WithOwner()
                                .HasForeignKey("GraphEdgeId");
                        });

                    b.Navigation("Properties")
                        .IsRequired();
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphNode.GraphNode", b =>
                {
                    b.HasOne("C4.Modules.Graph.Domain.ArchitectureGraph.ArchitectureGraph", null)
                        .WithMany("Nodes")
                        .HasForeignKey("ArchitectureGraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("C4.Modules.Graph.Domain.GraphNode.NodeProperties", "Properties", b1 =>
                        {
                            b1.Property<Guid>("GraphNodeId")
                                .HasColumnType("uuid");

                            b1.Property<double>("ClassificationConfidence")
                                .HasColumnType("double precision")
                                .HasColumnName("classification_confidence");

                            b1.Property<string>("ClassificationSource")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("classification_source");

                            b1.Property<decimal>("Cost")
                                .HasColumnType("numeric")
                                .HasColumnName("cost");

                            b1.Property<string>("Domain")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("domain");

                            b1.Property<bool>("IsInfrastructure")
                                .HasColumnType("boolean")
                                .HasColumnName("is_infrastructure");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("owner");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tags");

                            b1.Property<string>("Technology")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("technology");

                            b1.HasKey("GraphNodeId");

                            b1.ToTable("graph_nodes");

                            b1.WithOwner()
                                .HasForeignKey("GraphNodeId");
                        });

                    b.Navigation("Properties")
                        .IsRequired();
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.GraphSnapshot.GraphSnapshot", b =>
                {
                    b.HasOne("C4.Modules.Graph.Domain.ArchitectureGraph.ArchitectureGraph", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("ArchitectureGraphId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("C4.Modules.Graph.Domain.ArchitectureGraph.ArchitectureGraph", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
