// <auto-generated />
using System;
using C4.Modules.Feedback.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Feedback.Infrastructure.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    partial class FeedbackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C4.Modules.Feedback.Domain.FeedbackEntry.FeedbackEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Category", "SubmittedAtUtc");

                    b.ToTable("feedback_entries", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Feedback.Domain.Learning.LearningInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer");

                    b.Property<int>("InsightType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ProjectId", "Category");

                    b.ToTable("learning_insights", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Feedback.Domain.FeedbackEntry.FeedbackEntry", b =>
                {
                    b.OwnsOne("C4.Modules.Feedback.Domain.Corrections.ClassificationCorrection", "ClassificationCorrection", b1 =>
                        {
                            b1.Property<Guid>("FeedbackEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ArmResourceType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CorrectedC4Level")
                                .HasColumnType("text");

                            b1.Property<string>("CorrectedFriendlyName")
                                .HasColumnType("text");

                            b1.Property<bool?>("CorrectedIncludeInDiagram")
                                .HasColumnType("boolean");

                            b1.Property<string>("CorrectedServiceType")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalC4Level")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalFriendlyName")
                                .HasColumnType("text");

                            b1.Property<bool?>("OriginalIncludeInDiagram")
                                .HasColumnType("boolean");

                            b1.Property<string>("OriginalServiceType")
                                .HasColumnType("text");

                            b1.HasKey("FeedbackEntryId");

                            b1.ToTable("feedback_entries");

                            b1.ToJson("classification_correction");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackEntryId");
                        });

                    b.OwnsOne("C4.Modules.Feedback.Domain.Corrections.EdgeCorrection", "EdgeCorrection", b1 =>
                        {
                            b1.Property<Guid>("FeedbackEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CorrectedRelationship")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalRelationship")
                                .HasColumnType("text");

                            b1.Property<bool>("ShouldExist")
                                .HasColumnType("boolean");

                            b1.HasKey("FeedbackEntryId");

                            b1.ToTable("feedback_entries");

                            b1.ToJson("edge_correction");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackEntryId");
                        });

                    b.OwnsOne("C4.Modules.Feedback.Domain.Corrections.NodeCorrection", "NodeCorrection", b1 =>
                        {
                            b1.Property<Guid>("FeedbackEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CorrectedLevel")
                                .HasColumnType("text");

                            b1.Property<string>("CorrectedName")
                                .HasColumnType("text");

                            b1.Property<Guid?>("CorrectedParentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CorrectedServiceType")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalLevel")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalName")
                                .HasColumnType("text");

                            b1.Property<Guid?>("OriginalParentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OriginalServiceType")
                                .HasColumnType("text");

                            b1.HasKey("FeedbackEntryId");

                            b1.ToTable("feedback_entries");

                            b1.ToJson("node_correction");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackEntryId");
                        });

                    b.OwnsOne("C4.Modules.Feedback.Domain.FeedbackEntry.FeedbackRating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("FeedbackEntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.HasKey("FeedbackEntryId");

                            b1.ToTable("feedback_entries");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackEntryId");
                        });

                    b.OwnsOne("C4.Modules.Feedback.Domain.FeedbackEntry.FeedbackTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("FeedbackEntryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TargetId")
                                .HasColumnType("uuid")
                                .HasColumnName("target_id");

                            b1.Property<int>("TargetType")
                                .HasColumnType("integer")
                                .HasColumnName("target_type");

                            b1.HasKey("FeedbackEntryId");

                            b1.ToTable("feedback_entries");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackEntryId");
                        });

                    b.Navigation("ClassificationCorrection");

                    b.Navigation("EdgeCorrection");

                    b.Navigation("NodeCorrection");

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
