export type ServiceType = 'app' | 'api' | 'database' | 'queue' | 'cache' | 'storage' | 'monitoring' | 'external' | 'boundary';
export type TelemetryStatus = 'known' | 'unknown';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type TrafficState = 'green' | 'yellow' | 'red' | 'unknown';
export type DiffStatus = 'added' | 'removed' | 'unchanged';
export type DiagramLevel = 'Context' | 'Container' | 'Component' | 'Code' | 'Unknown';
export type SecuritySeverity = 'none' | 'low' | 'medium' | 'high' | 'critical';

export type DiagramNode = {
  id: string;
  label: string;
  externalResourceId?: string;
  level: DiagramLevel;
  health: 'green' | 'yellow' | 'red' | 'unknown';
  telemetryStatus?: TelemetryStatus;
  requestRate?: number;
  errorRate?: number;
  p95LatencyMs?: number;
  riskLevel?: RiskLevel;
  hourlyCostUsd?: number;
  drift?: boolean;
  serviceType: ServiceType;
  technology?: string;
  position?: { x: number; y: number };
  parentId?: string;
  environment?: string;
  resourceGroup?: string;
  domain?: string;
  tags?: string[];
  isInfrastructure?: boolean;
  classificationSource?: string;
  classificationConfidence?: number;
  groupKey?: string;
  securitySeverity?: SecuritySeverity;
  securityFindingCount?: number;
  diffStatus?: DiffStatus;
};

export type DiagramEdge = {
  id: string;
  from: string;
  to: string;
  traffic: number;
  trafficState?: TrafficState;
  trafficLabel?: string;
  requestRate?: number;
  errorRate?: number;
  p95LatencyMs?: number;
  protocol?: string;
  sourceExternalResourceId?: string;
  targetExternalResourceId?: string;
  diffStatus?: DiffStatus;
};
export type DiagramData = { nodes: DiagramNode[]; edges: DiagramEdge[] };
