// <auto-generated />
using System;
using C4.Modules.Discovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Discovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    partial class DiscoveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C4.Modules.Discovery.Domain.McpServers.McpServerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("mcp_server_configs", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Domain.Resources.DiscoveredResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "ResourceId")
                        .IsUnique();

                    b.ToTable("discovered_resources", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Domain.Subscriptions.AzureSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ExternalSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitPatToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitRepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("GitRootPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubscriptionId")
                        .IsUnique();

                    b.ToTable("azure_subscriptions", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Infrastructure.Persistence.AzureTokenEntity", b =>
                {
                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_subscription_id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.HasKey("ExternalSubscriptionId");

                    b.ToTable("azure_tokens", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Infrastructure.Persistence.DriftItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("drift_items", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Infrastructure.Persistence.ProjectArchitectureProfileEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoreDomains")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataSensitivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalDependencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastQuestionGenerationAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastResourceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemBoundaries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("project_architecture_profiles", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Infrastructure.Persistence.ProjectArchitectureQuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_architecture_questions", (string)null);
                });

            modelBuilder.Entity("C4.Modules.Discovery.Domain.Resources.DiscoveredResource", b =>
                {
                    b.OwnsOne("C4.Modules.Discovery.Domain.Resources.AzureResourceClassification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("DiscoveredResourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("C4Level")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ClassificationSource")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision");

                            b1.Property<string>("FriendlyName")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<bool>("IncludeInDiagram")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsInfrastructure")
                                .HasColumnType("boolean");

                            b1.Property<string>("ServiceType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("DiscoveredResourceId");

                            b1.ToTable("discovered_resources");

                            b1.WithOwner()
                                .HasForeignKey("DiscoveredResourceId");
                        });

                    b.Navigation("Classification");
                });
#pragma warning restore 612, 618
        }
    }
}
